# Documentation:
#   https://trivy.dev/docs/latest/configuration/filtering/

misconfigurations:
- id: AVD-DS-0011
  paths:
  - home/runner/.local/share/pipx/venvs/ansible/lib/python3.14/site-packages/ansible/galaxy/data/apb/Dockerfile.j2
  statement: This Dockerfile.j2 file is installed with pipx.

secrets:
- id: aws-access-key-id
  paths:
  - /home/runner/.local/share/pipx/venvs/ansible/lib/python3.14/site-packages/ansible_collections/community/aws/plugins/modules/__pycache__/sts_session_token.cpython-314.pyc
  - /home/runner/.local/share/pipx/venvs/ansible/lib/python3.14/site-packages/ansible_collections/community/aws/plugins/modules/sts_session_token.py
  statement: These are false positives.

vulnerabilities:
- id: CVE-2025-68121
  paths:
  - usr/local/bin/kustomize
  statement: The kustomize project needs to update their dependencies.
- id: CVE-2026-59873
  paths:
  - home/runner/externals/node24/lib/node_modules/npm/node_modules/tar/package.json
  statement: The base container needs to update their dependencies.
